### ISSUE TITLE
Component create fails on OpenShift 4.0

### ISSUE THREAD

**Issue by amitkrout** [redhat-developer/odo#1440]
[kind/bug]

## What versions of software are you using?
- Operating System: macOS
- Output of `odo version`: master
OpenShift Installer used - https://github.com/openshift/installer/releases/download/v0.14.0/openshift-install-linux-amd64
```
$ oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth

Server <hidden>:6443
kubernetes v1.12.4+0f8e04e
```

## How did you run odo exactly?
1. Got an openshift-dev AWS accounts to run OpenShift 4.0 installer
2. odo project create testcomponent
3. odo app create myapp
4. odo create nodejs nodejs --git https://github.com/openshift/nodejs-ex
```
$ odo create nodejs nodejs --git https://github.com/openshift/nodejs-ex
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1daa8ed]

goroutine 1 [running]:
github.com/redhat-developer/odo/pkg/odo/cli/component.(*CreateOptions).setCmpName(0xc0001a7860, 0xc00033e600, 0x2, 0x4, 0x6, 0x104390c)
        /Users/amit/go/src/github.com/redhat-developer/odo/pkg/odo/cli/component/create.go:161 +0xed
github.com/redhat-developer/odo/pkg/odo/cli/component.(*CreateOptions).Complete(0xc0001a7860, 0xc000a922d0, 0x6, 0xc0006f1b00, 0xc00033e600, 0x2, 0x4, 0x2, 0x25595f7)
        /Users/amit/go/src/github.com/redhat-developer/odo/pkg/odo/cli/component/create.go:313 +0xd7c
github.com/redhat-developer/odo/pkg/odo/genericclioptions.GenericRun(0x281ca40, 0xc0001a7860, 0xc0006f1b00, 0xc00033e600, 0x2, 0x4)
        /Users/amit/go/src/github.com/redhat-developer/odo/pkg/odo/genericclioptions/runnable.go:15 +0x6e
github.com/redhat-developer/odo/pkg/odo/cli/component.NewCmdCreate.func1(0xc0006f1b00, 0xc00033e600, 0x2, 0x4)
        /Users/amit/go/src/github.com/redhat-developer/odo/pkg/odo/cli/component/create.go:436 +0x5e
github.com/redhat-developer/odo/vendor/github.com/spf13/cobra.(*Command).execute(0xc0006f1b00, 0xc00033e5c0, 0x4, 0x4, 0xc0006f1b00, 0xc00033e5c0)
        /Users/amit/go/src/github.com/redhat-developer/odo/vendor/github.com/spf13/cobra/command.go:702 +0x289
github.com/redhat-developer/odo/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000683200, 0x0, 0x0, 0x5)
        /Users/amit/go/src/github.com/redhat-developer/odo/vendor/github.com/spf13/cobra/command.go:783 +0x29f
github.com/redhat-developer/odo/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /Users/amit/go/src/github.com/redhat-developer/odo/vendor/github.com/spf13/cobra/command.go:736
main.main()
        /Users/amit/go/src/github.com/redhat-developer/odo/cmd/odo/odo.go:73 +0x489
```

## Actual behavior
Fails as mentioned above

## Expected behavior
Should create the component

**Comment by amitkrout** [comment]
@kadel Could you please set the priority

**Comment by kadel** [comment]
@amitkrout can you please run the command in verbose mode?

**Comment by amitkrout** [comment]
@kadel 
```
$ odo create nodejs nodejs --git https://github.com/openshift/nodejs-ex -v 9
I0308 18:13:14.169407   92888 loader.go:359] Config loaded from file /Users/amit/installerOpenshiftAmit1/auth/kubeconfig
I0308 18:13:14.170556   92888 occlient.go:430] Trying to connect to server api.amit1.devcluster.openshift.com:6443
I0308 18:13:14.445938   92888 occlient.go:437] Server https://api.amit1.devcluster.openshift.com:6443 is up
I0308 18:13:14.446090   92888 round_trippers.go:386] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: odo/v0.0.0 (darwin/amd64) kubernetes/$Format" -H "Authorization: Bearer oVzq-z1BI-WzTvmFfGzBYEoy3QDX8Mc0K-sB6F9PdB4" 'https://api.amit1.devcluster.openshift.com:6443/apis/user.openshift.io/v1/users/~'
I0308 18:13:15.461560   92888 round_trippers.go:405] GET https://api.amit1.devcluster.openshift.com:6443/apis/user.openshift.io/v1/users/~ 200 OK in 1015 milliseconds
I0308 18:13:15.461589   92888 round_trippers.go:411] Response Headers:
I0308 18:13:15.461596   92888 round_trippers.go:414]     Audit-Id: 3e7a59df-520e-4c83-af0e-70aec2a250e8
I0308 18:13:15.461602   92888 round_trippers.go:414]     Cache-Control: no-store
I0308 18:13:15.461610   92888 round_trippers.go:414]     Cache-Control: no-store
I0308 18:13:15.461616   92888 round_trippers.go:414]     Content-Type: application/json
I0308 18:13:15.461623   92888 round_trippers.go:414]     Date: Fri, 08 Mar 2019 12:43:15 GMT
I0308 18:13:15.461628   92888 round_trippers.go:414]     Content-Length: 355
I0308 18:13:15.461666   92888 request.go:897] Response Body: {"kind":"User","apiVersion":"user.openshift.io/v1","metadata":{"name":"developer","selfLink":"/apis/user.openshift.io/v1/users/developer","uid":"c0741573-4193-11e9-9095-0a580a820029","resourceVersion":"130042","creationTimestamp":"2019-03-08T11:17:25Z"},"identities":["htpassidp:developer"],"groups":["system:authenticated","system:authenticated:oauth"]}
I0308 18:13:15.462405   92888 occlient.go:360] isLoggedIn err:  <nil> 
 output: "developer"
I0308 18:13:15.462491   92888 round_trippers.go:386] curl -k -v -XGET  -H "User-Agent: odo/v0.0.0 (darwin/amd64) kubernetes/$Format" -H "Authorization: Bearer oVzq-z1BI-WzTvmFfGzBYEoy3QDX8Mc0K-sB6F9PdB4" -H "Accept: application/json, */*" 'https://api.amit1.devcluster.openshift.com:6443/apis/project.openshift.io/v1/projects'
I0308 18:13:15.735854   92888 round_trippers.go:405] GET https://api.amit1.devcluster.openshift.com:6443/apis/project.openshift.io/v1/projects 200 OK in 273 milliseconds
I0308 18:13:15.735878   92888 round_trippers.go:411] Response Headers:
I0308 18:13:15.735884   92888 round_trippers.go:414]     Date: Fri, 08 Mar 2019 12:43:15 GMT
I0308 18:13:15.735890   92888 round_trippers.go:414]     Content-Length: 685
I0308 18:13:15.735895   92888 round_trippers.go:414]     Audit-Id: f1724ea6-fb6e-40e1-a64b-54b5a38fb098
I0308 18:13:15.735901   92888 round_trippers.go:414]     Cache-Control: no-store
I0308 18:13:15.735906   92888 round_trippers.go:414]     Cache-Control: no-store
I0308 18:13:15.735912   92888 round_trippers.go:414]     Content-Type: application/json
I0308 18:13:15.735940   92888 request.go:897] Response Body: {"kind":"ProjectList","apiVersion":"project.openshift.io/v1","metadata":{"selfLink":"/apis/project.openshift.io/v1/projects"},"items":[{"metadata":{"name":"testcomponent","selfLink":"/apis/project.openshift.io/v1/projects/testcomponent","uid":"9b130b41-419f-11e9-836f-023253a632de","resourceVersion":"184184","creationTimestamp":"2019-03-08T12:42:16Z","annotations":{"openshift.io/description":"","openshift.io/display-name":"","openshift.io/requester":"developer","openshift.io/sa.scc.mcs":"s0:c22,c4","openshift.io/sa.scc.supplemental-groups":"1000470000/10000","openshift.io/sa.scc.uid-range":"1000470000/10000"}},"spec":{"finalizers":["kubernetes"]},"status":{"phase":"Active"}}]}
I0308 18:13:15.736854   92888 context.go:231] Ignoring error as it usually means flag wasn't set: flag accessed but not defined: component
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1daa8ed]

goroutine 1 [running]:
github.com/redhat-developer/odo/pkg/odo/cli/component.(*CreateOptions).setCmpName(0xc0001eb860, 0xc000b09920, 0x2, 0x6, 0x3, 0x104390c)
        /Users/amit/go/src/github.com/redhat-developer/odo/pkg/odo/cli/component/create.go:161 +0xed
github.com/redhat-developer/odo/pkg/odo/cli/component.(*CreateOptions).Complete(0xc0001eb860, 0xc0009ded20, 0x6, 0xc000540d80, 0xc000b09920, 0x2, 0x6, 0x2, 0x25595f7)
        /Users/amit/go/src/github.com/redhat-developer/odo/pkg/odo/cli/component/create.go:313 +0xd7c
github.com/redhat-developer/odo/pkg/odo/genericclioptions.GenericRun(0x281ca40, 0xc0001eb860, 0xc000540d80, 0xc000b09920, 0x2, 0x6)
        /Users/amit/go/src/github.com/redhat-developer/odo/pkg/odo/genericclioptions/runnable.go:15 +0x6e
github.com/redhat-developer/odo/pkg/odo/cli/component.NewCmdCreate.func1(0xc000540d80, 0xc000b09920, 0x2, 0x6)
        /Users/amit/go/src/github.com/redhat-developer/odo/pkg/odo/cli/component/create.go:436 +0x5e
github.com/redhat-developer/odo/vendor/github.com/spf13/cobra.(*Command).execute(0xc000540d80, 0xc000b098c0, 0x6, 0x6, 0xc000540d80, 0xc000b098c0)
        /Users/amit/go/src/github.com/redhat-developer/odo/vendor/github.com/spf13/cobra/command.go:702 +0x289
github.com/redhat-developer/odo/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00070e000, 0x0, 0x0, 0x7)
        /Users/amit/go/src/github.com/redhat-developer/odo/vendor/github.com/spf13/cobra/command.go:783 +0x29f
github.com/redhat-developer/odo/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /Users/amit/go/src/github.com/redhat-developer/odo/vendor/github.com/spf13/cobra/command.go:736
main.main()
        /Users/amit/go/src/github.com/redhat-developer/odo/cmd/odo/odo.go:73 +0x489
```

**Comment by mohammedzee1000** [comment]
This is something that came up while we were investigating requirements for e2e tests on prow, using Opensift 4.0 cluster on AWS

**Comment by amitkrout** [comment]
Works fine with oc 4.0 (oc v4.0.0-0.139.0)

**Comment by mohammedzee1000** [comment]
> Works fine with oc 4.0 (oc v4.0.0-0.139.0)

Hmm ok that might solve that problem then :)

**Comment by kadel** [comment]
> Works fine with oc 4.0 (oc v4.0.0-0.139.0)

I'm confused here.

`oc` versions shouldn't have any effect on odo behaviour

**Comment by kadel** [comment]
I've tried to reproduce this, but no luck.

```
 ▶ odo create nodejs nodejs --git https://github.com/openshift/nodejs-ex
 ✓  Checking component
 ✓  Checking component version
 ✓  Initializing 'nodejs' component
 ✓  Creating component nodejs
 ✓  Triggering build from git
 ✓  Component 'nodejs' was created and port 8080/TCP was opened
 ✓  Component 'nodejs' is now set as active component
This may take a few moments to be ready

▶ odo push
Pushing changes to component: nodejs
 ✓  Triggering build from git
 ✓  Waiting for build to finish

▶ odo url create
 ✓  URL created for component: nodejs

nodejs-8080 - nodejs-8080-spring-boot-qwel-default.apps.tkral.devcluster.openshift.com


▶ curl --head nodejs-8080-spring-boot-qwel-default.apps.tkral.devcluster.openshift.com
HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: text/html; charset=utf-8
Content-Length: 40430
ETag: W/"9dee-3nm2OJV/pDUlKWUTQSk1Z/pOG6E"
Date: Mon, 11 Mar 2019 09:25:14 GMT
Set-Cookie: ad2df6d0c82aaa4c306445b1ccdcc47d=5f23994a909806687f48b0f1e8d2a8bd; path=/; HttpOnly
Cache-control: private
```



```
▶ odo version
odo v0.0.20 (964874a3)

Server: https://api.tkral.devcluster.openshift.com:6443
Kubernetes: v1.12.4+0f8e04e

▶ oc version
Client Version: version.Info{Major:"4", Minor:"0+", GitVersion:"v4.0.0-0.185.0", GitCommit:"e883da29bc", GitTreeState:"", BuildDate:"2019-02-25T13:48:37Z", GoVersion:"", Compiler:"", Platform:""}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2018-11-09T15:12:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by amitkrout** [comment]
I was trying a invalid scenario of ```Creating component using oc 3.11 on OpenShift cluster 4.0```. So it was failing. When i try the same component creation with oc 4.0 on same OpenShift cluster 4.0, it works.

So closing the issue
