### ISSUE TITLE
For component without context 'odo describe component-name --app=app-name --project=project-name' fails with SIGSEGV signal

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/odo#5432]
/kind bug

## What versions of software are you using?

**Operating System:** Linux

**Output of `odo version`:** odo v2.5.0 (724f16e68)

## How did you run odo exactly?

$ mkdir component-context

$ cd component-context

$ odo create nodejs-angular
...
$ odo push
...
$ odo describe
Component Name: nodejs-angular-component-na-ukwd
Type: angular
Environment Variables:
 · PROJECTS_ROOT=/project
 · PROJECT_SOURCE=/project
Storage:
 · dist of size 4Gi mounted to /project/dist/nodejs-angular
 · dist of size 4Gi mounted to /usr/share/nginx/html
URLs:
 · http://http-3baa0f80-storage-test.apps-crc.testing exposed via 8080
$ cd ..
$ odo describe nodejs-angular-component-na-ukwd --app app

## Actual behavior
```
URLs couldn't not be retrieved: unable to list routes: the component name, the app name or both are empty
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x88 pc=0x2285065]

goroutine 1 [running]:
github.com/redhat-developer/odo/pkg/envinfo.(*EnvInfo).ListStorage(0xc000ac1e90, 0x0, 0x0, 0x0, 0x0, 0x0)
	/builddir/build/BUILD/gocode/src/github.com/redhat-developer/odo/pkg/envinfo/storage.go:165 +0xa5
github.com/redhat-developer/odo/pkg/component.(*ComponentFullDescription).loadStoragesFromClientAndLocalConfig(0xc00023d340, 0x362d4d0, 0xc000ae8dd0, 0x3620b58, 0xc000ac1e60, 0x7ffca00cc268, 0x20, 0x7ffca00cc264, 0x3, 0xc000260b40, ...)
	/builddir/build/BUILD/gocode/src/github.com/redhat-developer/odo/pkg/component/component_full_description.go:68 +0xa3
github.com/redhat-developer/odo/pkg/component.NewComponentFullDescriptionFromClientAndLocalConfigProvider(0x362d4d0, 0xc000ae8dd0, 0xc000ac1e60, 0x7ffca00cc268, 0x20, 0x7ffca00cc264, 0x3, 0xc000456080, 0xc, 0xc00005607c, ...)
	/builddir/build/BUILD/gocode/src/github.com/redhat-developer/odo/pkg/component/component_full_description.go:188 +0x870
github.com/redhat-developer/odo/pkg/odo/cli/component.(*DescribeOptions).Run(0xc00012b5a8, 0x0, 0x0)
	/builddir/build/BUILD/gocode/src/github.com/redhat-developer/odo/pkg/odo/cli/component/describe.go:74 +0xa5
github.com/redhat-developer/odo/pkg/odo/genericclioptions.GenericRun(0x35dd850, 0xc00012b5a8, 0xc000749b80, 0xc000ade9f0, 0x1, 0x3)
	/builddir/build/BUILD/gocode/src/github.com/redhat-developer/odo/pkg/odo/genericclioptions/runnable.go:98 +0x46c
github.com/redhat-developer/odo/pkg/odo/cli/component.NewCmdDescribe.func1(0xc000749b80, 0xc000ade9f0, 0x1, 0x3)
	/builddir/build/BUILD/gocode/src/github.com/redhat-developer/odo/pkg/odo/cli/component/describe.go:102 +0x5e
github.com/spf13/cobra.(*Command).execute(0xc000749b80, 0xc000ade9c0, 0x3, 0x3, 0xc000749b80, 0xc000ade9c0)
	/builddir/build/BUILD/gocode/src/github.com/redhat-developer/odo/vendor/github.com/spf13/cobra/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc000533680, 0xc000120000, 0x2edbda0, 0x49e1fe8)
	/builddir/build/BUILD/gocode/src/github.com/redhat-developer/odo/vendor/github.com/spf13/cobra/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/builddir/build/BUILD/gocode/src/github.com/redhat-developer/odo/vendor/github.com/spf13/cobra/command.go:897
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/builddir/build/BUILD/gocode/src/github.com/redhat-developer/odo/vendor/github.com/spf13/cobra/command.go:890
main.main()
	/builddir/build/BUILD/gocode/src/github.com/redhat-developer/odo/cmd/odo/odo.go:70 +0x426
```

## Expected behavior
odo shows component description

## Any logs, error output, etc?
see above.

**Comment by dgolovin** [comment]
There is a similar issue for component without context https://github.com/redhat-developer/odo/issues/4135.

**Comment by valaparthvi** [comment]
Can you check again with bf906ffca45f53b06a0e409715dd1805f2476efd?

**Comment by dgolovin** [comment]
odo built from tag v2.5.0 fails, from [bf906ff](https://github.com/redhat-developer/odo/commit/bf906ffca45f53b06a0e409715dd1805f2476efd) works

**Comment by valaparthvi** [comment]
@kadel When will we release a new version of odo? This issue seems to be very common.

**Comment by kadel** [comment]
I hoped that we will be able to include https://github.com/redhat-developer/odo/pull/5314 in the next release :-/

**Comment by valaparthvi** [comment]
/close
I am going to close this issue since it's no longer relevant for v3. Let me know if you think otherwise.
With v3, it is possible to describe a component with `odo describe component --name <name> --namespace <namespace>`.
