### ISSUE TITLE
Panic when running `odo list namespaces` without an active Kubernetes context

### ISSUE THREAD

**Issue by rm3l** [redhat-developer/odo#6316]
/kind bug

## What versions of software are you using?

**Operating System:**
Fedora 37

**Output of `odo version`:**
```
odo v3.2.0 (ce42ce435)
```

## How did you run odo exactly?
Just ran `odo list namespaces` with no active Kubernetes context:

## Actual behavior
```
$ odo list namespaces
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x278ce00]

goroutine 1 [running]:
github.com/redhat-developer/odo/pkg/kclient.(*Client).GetCurrentNamespace(0x333d638?)
        /home/asoro/work/projects/odo/pkg/kclient/namespace.go:164
github.com/redhat-developer/odo/pkg/odo/genericclioptions.GenericRun({0x333e0f0, 0xc000a9cc60}, 0xc000884500, {0x46022b0, 0x0, 0x0})
        /home/asoro/work/projects/odo/pkg/odo/genericclioptions/runnable.go:184 +0xf82
github.com/redhat-developer/odo/pkg/odo/cli/list/namespace.NewCmdNamespaceList.func1(0xc000884500?, {0x46022b0?, 0x0?, 0x0?})
        /home/asoro/work/projects/odo/pkg/odo/cli/list/namespace/namespace.go:79 +0x38
github.com/spf13/cobra.(*Command).execute(0xc000884500, {0x46022b0, 0x0, 0x0})
        /home/asoro/work/projects/odo/vendor/github.com/spf13/cobra/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0xc00070e000)
        /home/asoro/work/projects/odo/vendor/github.com/spf13/cobra/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /home/asoro/work/projects/odo/vendor/github.com/spf13/cobra/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /home/asoro/work/projects/odo/vendor/github.com/spf13/cobra/command.go:895
main.main()
        /home/asoro/work/projects/odo/cmd/odo/odo.go:70 +0x425
```

## Expected behavior
`odo list namespaces` should not panic. 

All other commands (like `odo list bindings` or `odo describe component`) just display a nicer error message, e.g.:
```
$ odo list services     
 ✗  
Please ensure you have an active kubernetes context to your cluster. 
Consult your Kubernetes distribution's documentation for more details.
Error: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
```

## Any logs, error output, etc?
&mdash;

**Comment by valaparthvi** [comment]
Changing the subdep for `PROJECT` to `KUBERNETES` instead of `KUBERNETES_NULLABLE` should ensure that odo does not panic.
