### ISSUE TITLE
Completion panics

### ISSUE THREAD

**Issue by feloy** [redhat-developer/odo#6353]
/kind bug

## How did you run odo exactly?

```
$ odo <tab>
```

## Actual behavior

```
[phmartin@fedora empty]$ odo panic: runtime error: index out of range [-1]

goroutine 1 [running]:
github.com/redhat-developer/odo/pkg/odo/cli/list/namespace.NewCmdNamespaceList({0x2f570a3, 0x9}, {0xc000158ab0, 0x12})
	/home/phmartin/Documents/gits/odo/pkg/odo/cli/list/namespace/namespace.go:103 +0x3bf
github.com/redhat-developer/odo/pkg/odo/cli/list.NewCmdList({0x2f4f209, 0x4}, {0xc000aea498, 0x8})
	/home/phmartin/Documents/gits/odo/pkg/odo/cli/list/list.go:155 +0x305
github.com/redhat-developer/odo/pkg/odo/cli.odoRootCmd({0x3357e80, 0xc0004dae70}, {0x2f4e6fb, 0x3}, {0x2f4e6fb, 0x3})
	/home/phmartin/Documents/gits/odo/pkg/odo/cli/cli.go:183 +0x5ad
github.com/redhat-developer/odo/pkg/odo/cli.NewCmdOdo({0x3357e80?, 0xc0004dae70?}, {0x2f4e6fb?, 0x46248f0?}, {0x2f4e6fb?, 0xc0003a5b20?})
	/home/phmartin/Documents/gits/odo/pkg/odo/cli/cli.go:106 +0x34
main.main()
	/home/phmartin/Documents/gits/odo/cmd/odo/odo.go:38 +0x1a5
```

**Comment by anandrkskd** [comment]
@feloy can you add information about the `version` or `commit` of the odo binary, you're getting this error?

I tried it on latest main, and it works fine for me
```
-> % odo version
odo v3.3.0 (6172a16fc)

-> % odo add
add           build-images  create        deploy        dev           list          logout        preference    remove        version                                                                                                       
analyze       completion    delete        describe      init          login         logs          registry      set                   
```
