### ISSUE TITLE
odo describe binding crash

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/odo#6420]
/kind bug

## What versions of software are you using?

**Operating System:** Win11Pro

**Output of `odo version`:**

`odo v3.4.0 (b8662ef74)`

## How did you run odo exactly?

`odo describe binding`

## Actual behavior

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x187d19a]

goroutine 1 [running]:
github.com/redhat-developer/odo/pkg/binding.(*BindingClient).GetBindingsFromDevfile(0xc000823e80, {{{0xc00014e528, 0x5}, {0xc00046f3e0, 0x2d}, {0xc00046f380, 0x2d}, {0xc00029ca00, 0x1386, 0x1500}, ...}, ...}, ...)
        /builddir/build/BUILD/gocode/src/github.com/redhat-developer/odo/pkg/binding/binding.go:148 +0x3ba
github.com/redhat-developer/odo/pkg/odo/cli/describe.(*BindingOptions).runWithoutName(0xc000937bc0, {0x22924d8, 0xc0008d33e0})
        /builddir/build/BUILD/gocode/src/github.com/redhat-developer/odo/pkg/odo/cli/describe/binding.go:99 +0x105
github.com/redhat-developer/odo/pkg/odo/cli/describe.(*BindingOptions).Run(0x22924d8?, {0x22924d8?, 0xc0008d33e0?})
        /builddir/build/BUILD/gocode/src/github.com/redhat-developer/odo/pkg/odo/cli/describe/binding.go:69 +0x47
github.com/redhat-developer/odo/pkg/odo/genericclioptions.GenericRun({0x2292ee8, 0xc000937bc0}, 0xc000933400, {0x34a0428, 0x0, 0x0})
        /builddir/build/BUILD/gocode/src/github.com/redhat-developer/odo/pkg/odo/genericclioptions/runnable.go:278 +0x15cd
github.com/redhat-developer/odo/pkg/odo/cli/describe.NewCmdBinding.func1(0xc000933400?, {0x34a0428?, 0x0?, 0x0?})
        /builddir/build/BUILD/gocode/src/github.com/redhat-developer/odo/pkg/odo/cli/describe/binding.go:117 +0x38
github.com/spf13/cobra.(*Command).execute(0xc000933400, {0x34a0428, 0x0, 0x0})
        /builddir/build/BUILD/gocode/src/github.com/redhat-developer/odo/vendor/github.com/spf13/cobra/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001bcf00)
        /builddir/build/BUILD/gocode/src/github.com/redhat-developer/odo/vendor/github.com/spf13/cobra/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /builddir/build/BUILD/gocode/src/github.com/redhat-developer/odo/vendor/github.com/spf13/cobra/command.go:918
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /builddir/build/BUILD/gocode/src/github.com/redhat-developer/odo/vendor/github.com/spf13/cobra/command.go:911
main.main()
        /builddir/build/BUILD/gocode/src/github.com/redhat-developer/odo/cmd/odo/odo.go:83 +0x579
```

## Expected behavior

Binding should be listed

## Any logs, error output, etc?

[devfile.zip](https://github.com/redhat-developer/odo/files/10246319/devfile.zip)

**Comment by feloy** [comment]
More specifically, I think this error happens when no kubeconfig file has been found.

Thanks @jeffmaury for the report

**Comment by jeffmaury** [comment]
I have the kubeconfig but my Minikube cluster was stopped

**Comment by jeffmaury** [comment]
I think @dgolovin mention being blocked in offline mode but I can figure out if he created an issue or not.

**Comment by feloy** [comment]
> I think @dgolovin mention being blocked in offline mode but I can figure out if he created an issue or not.

I think @dgolovin's issue was https://github.com/redhat-developer/odo/issues/6379, but it is very related
