### ISSUE TITLE
`odo deploy` panics if there is no Kubeconfig

### ISSUE THREAD

**Issue by rm3l** [redhat-developer/odo#6694]
/kind bug
/area deploy

## What versions of software are you using?

**Operating System:**
Fedora 37

**Output of `odo version`:**
odo v3.8.0 (d0edfb678)

## How did you run odo exactly?

```
mkdir /tmp/bug-odo-deploy
cd /tmp/bug-odo-deploy

odo init --name bug-odo-deploy --devfile go --devfile-version 2.0.0

KUBECONFIG=/dev/null odo deploy
```

## Actual behavior

```
$ KUBECONFIG=/dev/null odo deploy                
panic: GetNamespace can be called only when clientset.KUBERNETES is added to dependencies

goroutine 1 [running]:
github.com/redhat-developer/odo/pkg/odo/context.GetNamespace({0x380ba18?, 0xc000b8e480?})
        /home/asoro/work/projects/odo/pkg/odo/context/kubernetes.go:26 +0x65
github.com/redhat-developer/odo/pkg/odo/cli/deploy.(*DeployOptions).Run(0xc0000155d0, {0x380ba18, 0xc000b8e480})
        /home/asoro/work/projects/odo/pkg/odo/cli/deploy/deploy.go:76 +0x8e
github.com/redhat-developer/odo/pkg/odo/genericclioptions.GenericRun({0x380c5b0, 0xc0000155d0}, 0xc00049c600, {0x4ccbe68, 0x0, 0x0})
        /home/asoro/work/projects/odo/pkg/odo/genericclioptions/runnable.go:282 +0x1659
github.com/redhat-developer/odo/pkg/odo/cli/deploy.NewCmdDeploy.func1(0xc00049c600?, {0x4ccbe68?, 0x0?, 0x0?})
        /home/asoro/work/projects/odo/pkg/odo/cli/deploy/deploy.go:108 +0x38
github.com/spf13/cobra.(*Command).execute(0xc00049c600, {0x4ccbe68, 0x0, 0x0})
        /home/asoro/work/projects/odo/vendor/github.com/spf13/cobra/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc00084e000)
        /home/asoro/work/projects/odo/vendor/github.com/spf13/cobra/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/asoro/work/projects/odo/vendor/github.com/spf13/cobra/command.go:968
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /home/asoro/work/projects/odo/vendor/github.com/spf13/cobra/command.go:961
main.main()
        /home/asoro/work/projects/odo/cmd/odo/odo.go:83 +0x585
```

## Expected behavior
It should not panic but return a nicer error message.

**Comment by rm3l** [comment]
This should be fixed with #6688, which has a similar issue at command validation time.
