### ISSUE TITLE
`odo dev` freezes then panics when run from `~`

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/odo#6780]
/kind bug

## What versions of software are you using?

**Operating System:**

RHEL 8.7

**Output of `odo version`:**

```
odo v3.9.0 (8cb53c2a0)

Server: https://api.crc.testing:6443
Kubernetes: v1.24.0+3882f8f
```

## How did you run odo exactly?

(assuming there is no devfile in `~`):

```
cd
odo dev
```

## Actual behavior

It freezes:

![odo-dev-homedir](https://user-images.githubusercontent.com/22376627/234939783-4f835749-4461-4453-a8d4-83bb64e1885f.gif)

Eventually, it panics with the logs below.

## Expected behavior

The interactive wizard to select a devfile starts.

## Any logs, error output, etc?

```
panic: regexp: Compile(`(let|const|var)\s+.profile/* %v *//convert/etc/ssh/gid_map/healthz/metrics/mutate-/uid_map/vendor//version000000000123456715:04:051606nict1694acad1959acad2.5.4.102.5.4.112.5.4.172006-1-238;5;%d;3des-cbc4882812548;5;%d;:*(\d+\s*=\s*([^;]*)`): error parsing regexp: missing closing ): `(let|const|var)\s+.profile/* %v *//convert/etc/ssh/gid_map/healthz/metrics/mutate-/uid_map/vendor//version000000000123456715:04:051606nict1694acad1959acad2.5.4.102.5.4.112.5.4.172006-1-238;5;%d;3des-cbc4882812548;5;%d;:*(\d+\s*=\s*([^;]*)`

goroutine 1 [running]:
regexp.MustCompile({0xc001ff8000, 0xee})
        /usr/lib/golang/src/regexp/regexp.go:319 +0xbb
github.com/redhat-developer/alizer/go/pkg/apis/enricher/framework/javascript/nodejs.getPort({0xc038ce2000, 0x48f81f8}, {0xc0160bc150, 0xffffffffffffffff?, 0x33f38f8?})
        /builddir/build/BUILD/gocode/src/github.com/redhat-developer/odo/vendor/github.com/redhat-developer/alizer/go/pkg/apis/enricher/framework/javascript/nodejs/express_detector.go:86 +0x199
github.com/redhat-developer/alizer/go/pkg/apis/enricher/framework/javascript/nodejs.ExpressDetector.DoPortsDetection({}, 0xc008546960, 0xd?)
        /builddir/build/BUILD/gocode/src/github.com/redhat-developer/odo/vendor/github.com/redhat-developer/alizer/go/pkg/apis/enricher/framework/javascript/nodejs/express_detector.go:51 +0x20b
github.com/redhat-developer/alizer/go/pkg/apis/enricher.JavaScriptEnricher.DoEnrichComponent({}, 0xc008546960, {{0xc00005e0dc, 0xe}, {0xc0008e48e8, 0x3, 0x3}}, 0x4f49c50?)
        /builddir/build/BUILD/gocode/src/github.com/redhat-developer/odo/vendor/github.com/redhat-developer/alizer/go/pkg/apis/enricher/javascript_enricher.go:94 +0x5e8
github.com/redhat-developer/alizer/go/pkg/apis/recognizer.enrichComponent(0xc008546960, {{0xc00005e0dc, 0xe}, {0xc0008e48e8, 0x3, 0x3}}, 0xc0008322a0?)
        /builddir/build/BUILD/gocode/src/github.com/redhat-developer/odo/vendor/github.com/redhat-developer/alizer/go/pkg/apis/recognizer/component_recognizer.go:331 +0x89
github.com/redhat-developer/alizer/go/pkg/apis/recognizer.detectComponentByAnalyzingConfigFile({0xc00a2673e0, 0x5a}, {0xc000cfff50, 0xa}, {{0xc00005e0dc, 0xe}, {0xc0008e48e8, 0x3, 0x3}}, 0xc001010a90)
        /builddir/build/BUILD/gocode/src/github.com/redhat-developer/odo/vendor/github.com/redhat-developer/alizer/go/pkg/apis/recognizer/component_recognizer.go:303 +0x3ae
github.com/redhat-developer/alizer/go/pkg/apis/recognizer.detectComponentUsingConfigFile({0xc00a2673e0, 0x5a}, {0xc0010aa040?, 0x2, 0x2}, {{0xc00005e0dc, 0xe}, {0xc0008e48e8, 0x3, 0x3}}, ...)
        /builddir/build/BUILD/gocode/src/github.com/redhat-developer/odo/vendor/github.com/redhat-developer/alizer/go/pkg/apis/recognizer/component_recognizer.go:316 +0x15a
github.com/redhat-developer/alizer/go/pkg/apis/recognizer.DetectComponentsFromFilesList({0xc0193fa000, 0x161375, 0xc001010a90?}, {{0xc00005e0dc, 0xe}, {0xc0008e48e8, 0x3, 0x3}}, 0xc0008e48e8?)
        /builddir/build/BUILD/gocode/src/github.com/redhat-developer/odo/vendor/github.com/redhat-developer/alizer/go/pkg/apis/recognizer/component_recognizer.go:229 +0x327
github.com/redhat-developer/alizer/go/pkg/apis/recognizer.detectComponentsWithSettings({{0xc00005e0dc, 0xe}, {0xc0008e48e8, 0x3, 0x3}}, 0xc000a34a80?)
        /builddir/build/BUILD/gocode/src/github.com/redhat-developer/odo/vendor/github.com/redhat-developer/alizer/go/pkg/apis/recognizer/component_recognizer.go:86 +0xa5
github.com/redhat-developer/alizer/go/pkg/apis/recognizer.detectComponentsWithPathAndPortStartegy(...)
        /builddir/build/BUILD/gocode/src/github.com/redhat-developer/odo/vendor/github.com/redhat-developer/alizer/go/pkg/apis/recognizer/component_recognizer.go:55
github.com/redhat-developer/alizer/go/pkg/apis/recognizer.DetectComponents({0xc00005e0dc, 0xe})
        /builddir/build/BUILD/gocode/src/github.com/redhat-developer/odo/vendor/github.com/redhat-developer/alizer/go/pkg/apis/recognizer/component_recognizer.go:34 +0xd1
github.com/redhat-developer/alizer/go/pkg/apis/recognizer.selectDevFilesFromComponentsDetectedInPath({0xc00005e0dc, 0xe}, {0xc000a11200, 0x19, 0x20})
        /builddir/build/BUILD/gocode/src/github.com/redhat-developer/odo/vendor/github.com/redhat-developer/alizer/go/pkg/apis/recognizer/devfile_recognizer.go:51 +0x65
github.com/redhat-developer/alizer/go/pkg/apis/recognizer.SelectDevFilesFromTypes({0xc00005e0dc, 0xe}, {0xc000a11200, 0x19, 0x20})
        /builddir/build/BUILD/gocode/src/github.com/redhat-developer/odo/vendor/github.com/redhat-developer/alizer/go/pkg/apis/recognizer/devfile_recognizer.go:28 +0x54
github.com/redhat-developer/alizer/go/pkg/apis/recognizer.SelectDevFileFromTypes(...)
        /builddir/build/BUILD/gocode/src/github.com/redhat-developer/odo/vendor/github.com/redhat-developer/alizer/go/pkg/apis/recognizer/devfile_recognizer.go:67
github.com/redhat-developer/odo/pkg/alizer.(*Alizer).DetectFramework(0xc00006c000?, {0x3854d98?, 0xc000b1e000?}, {0xc00005e0dc, 0xe})
        /builddir/build/BUILD/gocode/src/github.com/redhat-developer/odo/pkg/alizer/alizer.go:46 +0x23a
github.com/redhat-developer/odo/pkg/init/backend.(*AlizerBackend).SelectDevfile(0xc000690b00, {0x3854d98?, 0xc000b1e000?}, 0x11b0fc7?, {0xc0007a10f0?, 0xc0007a1150?}, {0xc00005e0dc, 0xe})
        /builddir/build/BUILD/gocode/src/github.com/redhat-developer/odo/pkg/init/backend/alizer.go:38 +0xb0
github.com/redhat-developer/odo/pkg/init.(*InitClient).SelectDevfile(0xc00072c4b0, {0x3854d98, 0xc000b1e000}, 0xc000b1e150, {0x386a6c0, 0x4f49c50}, {0xc00005e0dc, 0xe})
        /builddir/build/BUILD/gocode/src/github.com/redhat-developer/odo/pkg/init/init.go:94 +0x117
github.com/redhat-developer/odo/pkg/init.(*InitClient).SelectAndPersonalizeDevfile(0xc00072c4b0, {0x3854d98, 0xc000b1e000}, 0x21?, {0xc00005e0dc, 0xe})
        /builddir/build/BUILD/gocode/src/github.com/redhat-developer/odo/pkg/init/init.go:277 +0x97
github.com/redhat-developer/odo/pkg/init.(*InitClient).InitDevfile(0xc00072c4b0, {0x3854d98, 0xc000b1e000}, 0xc000b1e090, {0xc00005e0dc, 0xe}, 0xc000b1e0c0, 0xc000690b80)
        /builddir/build/BUILD/gocode/src/github.com/redhat-developer/odo/pkg/init/init.go:323 +0x128
github.com/redhat-developer/odo/pkg/odo/genericclioptions.runPreInit({0x3854d98, 0xc000b1e000}, {0xc00005e0dc, 0xe}, 0xc0005ae000, {0x3865160, 0xc0005987b8}, {0x348db8e, 0x59})
        /builddir/build/BUILD/gocode/src/github.com/redhat-developer/odo/pkg/odo/genericclioptions/init.go:32 +0x1d9
github.com/redhat-developer/odo/pkg/odo/genericclioptions.GenericRun({0x38559d8, 0xc00019a5a0}, 0xc00016a300, {0x4f49c50, 0x0, 0x0})
        /builddir/build/BUILD/gocode/src/github.com/redhat-developer/odo/pkg/odo/genericclioptions/runnable.go:242 +0x1334
github.com/redhat-developer/odo/pkg/odo/cli/dev.NewCmdDev.func1(0xc00016a300?, {0x4f49c50?, 0x0?, 0x0?})
        /builddir/build/BUILD/gocode/src/github.com/redhat-developer/odo/pkg/odo/cli/dev/dev.go:235 +0x38
github.com/spf13/cobra.(*Command).execute(0xc00016a300, {0x4f49c50, 0x0, 0x0})
        /builddir/build/BUILD/gocode/src/github.com/redhat-developer/odo/vendor/github.com/spf13/cobra/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc000120000)
        /builddir/build/BUILD/gocode/src/github.com/redhat-developer/odo/vendor/github.com/spf13/cobra/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /builddir/build/BUILD/gocode/src/github.com/redhat-developer/odo/vendor/github.com/spf13/cobra/command.go:968
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /builddir/build/BUILD/gocode/src/github.com/redhat-developer/odo/vendor/github.com/spf13/cobra/command.go:961
main.main()
        /builddir/build/BUILD/gocode/src/github.com/redhat-developer/odo/cmd/odo/odo.go:83 +0x585
```

**Comment by valaparthvi** [comment]
`odo` has really frozen, but is simply analyzing your non-empty directory to determine a suitable Devfile. Since your home directory contains a fair amount of files, it takes more time to analyze it, giving the impression that it has frozen.
We will try to make this better on our end by adding a message/spinner on the screen.
